CREATE TABLE account(
	id INT NOT NULL IDENTITY(1,1),
	name VARCHAR(128) NOT NULL,
	username VARCHAR(128) NOT NULL,
	email VARCHAR(128) NOT NULL,
	password VARCHAR(128) NOT NULL,
	interests VARCHAR(500) NULL,
	profile_picture VARCHAR(500) NULL,
	PRIMARY KEY(email)
);
